cloud:
aws:
region:
static: eu-central-1
stack:
auto: false
credentials:
accessKey: AKIAQIPEBO7UI6Q5GDL5
secretKey: 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

application:
bucket:
name: theeagle

logging:
level:
com:
amazonaws:
util:
EC2MetadataUtils: error